/* Camada REAL: Supabase Auth + banco multiusuário + Storage + Mercado Pago API */
(async()=>{
  try{
    const cfg=await fetch('/api/config',{cache:'no-store'}).then(r=>r.json());
    if(!cfg.supabaseUrl||!cfg.supabaseAnonKey){console.warn('MiniLine: backend ainda não configurado.');return;}
    if(!window.supabase){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=no;document.head.appendChild(s)});}
    const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    window.MLX_SUPABASE=sb;
    const K={products:'mlx_products_v3',users:'mlx_users_v3',session:'mlx_session_v3'};
    const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
    async function localizeSession(){const {data:{session}}=await sb.auth.getSession();if(session?.user){const u=session.user;put(K.users,[{id:u.id,name:u.user_metadata?.full_name||u.email?.split('@')[0]||'Cliente',email:u.email,avatar:u.user_metadata?.avatar_url||'',createdAt:Date.now()}]);put(K.session,{userId:u.id});}else{localStorage.removeItem(K.session);}}
    async function syncProducts(){const r=await fetch('/api/products');if(!r.ok)return;const j=await r.json();if(Array.isArray(j.products)){const mapped=j.products.map(p=>({...p,id:p.id,ownerId:p.owner_id, seller:p.profiles?.display_name||p.seller_name||'Vendedor', createdAt:new Date(p.created_at).getTime(), images:Array.isArray(p.images)?p.images:[], type:p.type, entry:p.entry_price??(p.type==='presale'?25:null), balance:p.balance_price??(p.type==='presale'?Math.max(0,p.price-25):null), rating:p.profiles?.rating||5, sales:p.profiles?.sales_count||0,storeName:p.profiles?.store_name||'',storeSlug:p.profiles?.store_slug||'',storeLogo:p.profiles?.store_logo||'',storeBanner:p.profiles?.store_banner||'',storeBio:p.profiles?.store_bio||'',sellerStatus:p.profiles?.seller_status||'none'}));put(K.products,mapped);window.dispatchEvent(new Event('mlx:remote-ready'));}}
    await localizeSession(); await syncProducts();
    sb.auth.onAuthStateChange(async(_e,session)=>{if(session){await localizeSession();}else{localStorage.removeItem(K.session);localStorage.removeItem(K.users);}});

    function addGoogle(){const f=document.querySelector('#loginForm');if(!f||f.querySelector('[data-google-login]'))return;const b=document.createElement('button');b.type='button';b.className='button google-login';b.dataset.googleLogin='1';b.textContent='Continuar com Google';f.appendChild(b);b.onclick=async()=>{const next=new URLSearchParams(location.search).get('next')||'conta.html';sessionStorage.setItem('mlx_next',next);const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/login.html?oauth=1&next='+encodeURIComponent(next)}});if(error)alert(error.message)};}
    addGoogle();
    const oauth=new URLSearchParams(location.search).get('oauth');if(oauth){await localizeSession();const next=new URLSearchParams(location.search).get('next')||sessionStorage.getItem('mlx_next')||'conta.html';if((await sb.auth.getSession()).data.session)location.replace(next);}

    const login=document.querySelector('#loginForm');if(login){login.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const email=login.email.value.trim(),password=login.password.value;if(password.length<6)return alert('A senha precisa ter pelo menos 6 caracteres.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert(error.message);await localizeSession();location.href=new URLSearchParams(location.search).get('next')||'conta.html';},true)}
    const reg=document.querySelector('#registerForm');if(reg){reg.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const name=reg.name.value.trim(),email=reg.email.value.trim(),password=reg.password.value;if(name.length<2)return alert('Informe seu nome.');if(password.length<6)return alert('A senha precisa ter pelo menos 6 caracteres.');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return alert(error.message);if(data.session){await localizeSession();location.href='conta.html'}else alert('Cadastro criado. Verifique seu e-mail para confirmar a conta.');},true)}

    async function gateSellerPage(){
      const form=document.querySelector('#sellForm'); if(!form)return;
      const {data:{session}}=await sb.auth.getSession();
      if(!session)return;
      const r=await fetch('/api/sellers?id='+encodeURIComponent(session.user.id),{headers:{Authorization:'Bearer '+session.access_token}}); if(!r.ok)return;
      const j=await r.json(); const st=j.store?.seller_status||'none';
      if(st!=='approved'){
        const card=document.createElement('div'); card.className='card seller-status '+st; card.innerHTML=st==='pending'?'<strong>Conta de vendedor em análise</strong><p>Aguarde a autorização do administrador para publicar anúncios.</p><a class="button ghost" href="conta-vendedor.html">Ver minha solicitação</a>':st==='rejected'?'<strong>Solicitação de vendedor recusada</strong><p>Corrija as informações da sua loja e envie novamente.</p><a class="button primary" href="conta-vendedor.html">Corrigir loja</a>':'<strong>Ative sua conta de vendedor</strong><p>Você precisa criar a loja e enviar as informações para análise antes de publicar.</p><a class="button primary" href="conta-vendedor.html">Criar conta de vendedor</a>'; form.replaceWith(card);
      }
    }
    gateSellerPage();

    async function publishFromForm(form, isAdmin){
      const {data:{session}}=await sb.auth.getSession();
      if(!session){location.href='login.html?next='+encodeURIComponent(location.pathname.split('/').pop());return;}
      const fd=new FormData(form); const imgs=[...form.querySelectorAll('.photo-previews img')].map(x=>x.src).filter(x=>x.startsWith('data:')).slice(0,8);
      if(!imgs.length){alert('Adicione pelo menos uma foto.');return;}
      const images=[];
      for(const data of imgs){const r=await fetch('/api/upload-image',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({data})});const j=await r.json().catch(()=>({}));if(!r.ok)return alert(j.error||'Falha ao enviar imagem.');images.push(j.url);}
      const payload={name:String(fd.get('name')||'').trim(),category:String(fd.get('category')||'Miniaturas').trim(),description:String(fd.get('description')||'').trim(),price:Number(fd.get('price')),stock:Number(fd.get('stock')),type:fd.get('type')||'ready',arrival:fd.get('arrival')||null,time:fd.get('time')||null,condition:fd.get('condition')||null,shipping:fd.get('shipping')||null,images};
      if(!payload.name||payload.price<=0||payload.stock<0)return alert('Confira nome, preço e estoque.');
      if(payload.type==='presale'&&!payload.arrival)return alert('Informe a data de chegada da pré-venda.');
      const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)return alert(j.error||'Não foi possível publicar.');
      localStorage.setItem('mlx_products_v3',JSON.stringify([j.product,...JSON.parse(localStorage.getItem('mlx_products_v3')||'[]').filter(x=>x.id!==j.product.id)]));
      alert('Anúncio publicado no catálogo para todos os clientes.');location.href='produto.html?id='+encodeURIComponent(j.product.id);
    }
    // Capture antes do código antigo: publicação e administração deixam de depender de localStorage.
    document.querySelector('#sellForm')?.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();publishFromForm(e.currentTarget,false)},true);
    document.querySelector('#adminProductForm')?.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();publishFromForm(e.currentTarget,true)},true);

    const finish=document.querySelector('#finishOrder');if(finish){finish.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();const {data:{session}}=await sb.auth.getSession();if(!session)return location.href='login.html?next=checkout.html';const allCart=JSON.parse(localStorage.getItem('mlx_cart_v3')||'[]');const ids=new URLSearchParams(location.search).get('items')?.split(',').filter(Boolean)||JSON.parse(localStorage.getItem('mlx_selected_cart_v3')||'[]');const cart=allCart.filter(i=>ids.includes(i.id));if(!cart.length)return alert('Selecione pelo menos um produto.');const address={};['cep','street','number','city','state'].forEach(id=>address[id]=document.querySelector('#'+id)?.value.trim());if(Object.values(address).some(v=>!v))return alert('Preencha o endereço completo.');const payment=document.querySelector('#payment')?.value||'Pix';const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({items:cart,address,payment})});const j=await r.json();if(!r.ok)return alert(j.error||'Erro ao criar pedido.');const p=await fetch('/api/payment',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({orderId:j.order.id})});const pj=await p.json();if(!p.ok)return alert(pj.error||'Pedido criado, mas pagamento não foi iniciado.');location.href=pj.init_point;},true)}

    async function uploadDataUrl(data,session){
      const r=await fetch('/api/upload-image',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({data})});
      const j=await r.json().catch(()=>({})); if(!r.ok)throw new Error(j.error||'Falha no upload.'); return j.url;
    }
    async function setupSellerAccount(){
      const root=document.querySelector('#sellerAccountApp'); if(!root)return;
      const {data:{session}}=await sb.auth.getSession();
      if(!session){root.innerHTML='<div class="card"><h2>Entre para criar sua loja</h2><p class="page-subtitle">A conta comum continua disponível sem precisar criar uma conta de vendedor.</p><a class="button primary" href="login.html?next=conta-vendedor.html">Entrar</a></div>';return;}
      const r=await fetch('/api/sellers?id='+encodeURIComponent(session.user.id),{headers:{Authorization:'Bearer '+session.access_token}}); const data=r.ok?await r.json():{}; const current=data.store||null;
      const status=current?.seller_status||'none', editable=status==='approved';
      const title=status==='approved'?'Sua loja está ativa':status==='pending'?'Solicitação em análise':status==='rejected'?'Solicitação recusada':'Crie sua loja de vendedor';
      root.innerHTML=`<div class="seller-form-card card"><div class="seller-status ${status}"><strong>${title}</strong><p>${status==='approved'?'Você já pode publicar anúncios e personalizar sua vitrine.':status==='pending'?'O administrador precisa verificar as informações fornecidas antes da ativação.':status==='rejected'?'Corrija as informações e envie novamente.':'Preencha as informações obrigatórias. A ativação será feita pelo administrador.'}</p></div><form id="sellerStoreForm"><div class="form-grid"><div class="form-group"><label class="form-label">Nome da loja *</label><input class="form-input" name="store_name" required value="${esc(current?.store_name||'')}"></div><div class="form-group"><label class="form-label">Identificador da loja *</label><input class="form-input" name="store_slug" required pattern="[a-zA-Z0-9-]+" value="${esc(current?.store_slug||'')}" placeholder="minha-loja"></div><div class="form-group full"><label class="form-label">Logo da loja ${editable?'':'*'}</label><input class="form-input" id="sellerLogo" type="file" accept="image/*" ${editable?'':'required'}><small>Imagem quadrada recomendada.</small><div id="sellerLogoPreview" class="photo-previews"></div></div><div class="form-group full"><label class="form-label">Banner personalizado ${editable?'':'*'}</label><input class="form-input" id="sellerBanner" type="file" accept="image/*" ${editable?'':'required'}><small>Banner exclusivo da sua vitrine.</small><div id="sellerBannerPreview" class="photo-previews"></div></div><div class="form-group full"><label class="form-label">Descrição da loja</label><textarea class="form-textarea" name="store_bio" maxlength="500" placeholder="Conte sobre sua loja e sua coleção.">${esc(current?.store_bio||'')}</textarea></div></div><button class="button primary">${editable?'Salvar personalização':'Enviar para autorização'}</button></form></div>`;
      const fileData=input=>new Promise((resolve,reject)=>{const f=input?.files?.[0];if(!f)return resolve(null);const rd=new FileReader();rd.onload=()=>resolve(rd.result);rd.onerror=reject;rd.readAsDataURL(f)});
      const preview=(input,target)=>input?.addEventListener('change',async()=>{const d=await fileData(input);if(d)document.querySelector(target).innerHTML=`<div class="photo-preview"><img src="${d}" alt="Pré-visualização"></div>`});
      preview(document.querySelector('#sellerLogo'),'#sellerLogoPreview'); preview(document.querySelector('#sellerBanner'),'#sellerBannerPreview');
      document.querySelector('#sellerStoreForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{let logo=current?.store_logo||null,banner=current?.store_banner||null;const ld=await fileData(document.querySelector('#sellerLogo')),bd=await fileData(document.querySelector('#sellerBanner'));if(ld)logo=await uploadDataUrl(ld,session);if(bd)banner=await uploadDataUrl(bd,session);if(!logo||!banner)throw new Error('Logo e banner são obrigatórios para criar a loja.');const action=editable?'update_store':'apply';const rr=await fetch('/api/sellers',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({action,store_name:fd.get('store_name'),store_slug:fd.get('store_slug'),store_logo:logo,store_banner:banner,store_bio:fd.get('store_bio')})});const jj=await rr.json().catch(()=>({}));if(!rr.ok)throw new Error(jj.error||'Falha ao salvar.');alert(editable?'Loja atualizada.':'Solicitação enviada para o administrador.');location.reload()}catch(err){alert(err.message)}});
    }
    setupSellerAccount();

    async function loadAdmin(){
      const form=document.querySelector('#adminNotificationForm');
      if(!form)return;
      const {data:{session}}=await sb.auth.getSession();if(!session){location.href='login.html?next=admin.html';return;}
      const r=await fetch('/api/admin',{headers:{Authorization:'Bearer '+session.access_token}});const j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||'Acesso negado.');location.href='index.html';return;}
      const sel=document.querySelector('#notificationTarget');for(const u of (j.users||[])){const o=document.createElement('option');o.value=u.id;o.textContent=(u.name||u.email||u.id)+' — '+(u.email||'');sel.appendChild(o)}
      const ul=document.querySelector('#adminUsersList');if(ul)ul.innerHTML=(j.users||[]).map(u=>`<div class="admin-product"><section><b>${u.name||'Cliente'}</b><small>${u.email||''} · ${u.role||'customer'}</small></section></div>`).join('')||'<div class="empty-state">Nenhum usuário.</div>';
      const sellerList=document.querySelector('#adminSellerList');
      if(sellerList){const pending=(j.users||[]).filter(u=>u.seller_status==='pending');sellerList.innerHTML=pending.length?pending.map(u=>`<div class="admin-seller-card"><div class="admin-seller-avatar">${u.store_logo?`<img src="${u.store_logo}" alt="" style="width:100%;height:100%;object-fit:cover">`:esc((u.store_name||u.display_name||'L').slice(0,1).toUpperCase())}</div><section><b>${esc(u.store_name||'Loja sem nome')}</b><small>${esc(u.display_name||'')} · ${esc(u.email||'')}<br>${esc(u.store_bio||'')}</small></section><div class="admin-seller-actions"><button class="button primary" data-seller-review="approve" data-user="${u.id}">Autorizar</button><button class="button danger" data-seller-review="reject" data-user="${u.id}">Recusar</button></div></div>`).join(''):'<div class="empty-state">Nenhuma solicitação de vendedor pendente.</div>';sellerList.querySelectorAll('[data-seller-review]').forEach(b=>b.onclick=async()=>{const decision=b.dataset.sellerReview;const reason=decision==='reject'?(prompt('Motivo da recusa (opcional):')||''):'';const rr=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({action:'seller_review',user_id:b.dataset.user,decision,reason})});const jj=await rr.json().catch(()=>({}));if(!rr.ok)return alert(jj.error||'Falha ao revisar vendedor.');alert(decision==='approve'?'Conta autorizada.':'Solicitação recusada.');loadAdmin()})}
      const ol=document.querySelector('#adminOrdersList');if(ol)ol.innerHTML=(j.orders||[]).map(o=>`<div class="admin-product"><section><b>Pedido ${o.id}</b><small>${o.status} · ${Number(o.total_now||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · ${new Date(o.created_at).toLocaleString('pt-BR')}</small></section></div>`).join('')||'<div class="empty-state">Nenhum pedido.</div>';
      form.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(form);const rr=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({action:'notification',target:d.get('target'),title:d.get('title'),message:d.get('message')})});const jj=await rr.json().catch(()=>({}));if(!rr.ok)return alert(jj.error||'Falha ao enviar.');alert('Notificação enviada e salva no servidor.');form.reset();});
    }
    await loadAdmin();
    window.addEventListener('mlx:remote-ready',()=>{try{const a=JSON.parse(localStorage.getItem('mlx_products_v3')||'[]');if(a.length)window.dispatchEvent(new Event('mlx:products-updated'));}catch{}});
    const nroot=document.querySelector('#notifications');
    if(nroot){const {data:{session}}=await sb.auth.getSession();if(session){const nr=await fetch('/api/notifications',{headers:{Authorization:'Bearer '+session.access_token}});const nj=await nr.json().catch(()=>({}));if(nr.ok&&Array.isArray(nj.notifications)){put('mlx_notifications_v3',nj.notifications.map(n=>({id:n.id,title:n.title,text:n.message,date:new Date(n.created_at).toLocaleString('pt-BR'),read:false,userId:n.target==='all'?null:n.target})));if(!sessionStorage.getItem('mlx_notif_synced')){sessionStorage.setItem('mlx_notif_synced','1');location.reload();}else sessionStorage.removeItem('mlx_notif_synced');}}}
    document.addEventListener('click',async e=>{const b=e.target.closest('#logoutBtn');if(b&&window.MLX_SUPABASE){e.preventDefault();await sb.auth.signOut();location.href='index.html';}},true);

  }catch(e){console.error('MiniLine real backend',e)}
})();
